### ISSUE TITLE
Настроить взаимодействие между серверами

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateBackend#10]
Решаем задачу поэтапно:

- [x] К презентации установить модуль CORS на сервер Python-а
- [x] Далее настроить DNS

**Comment by olgapshen** [comment]
Думаю можно в In progress перевести.

**Comment by sshiae** [comment]
На счёт DNS, можно купить домен у одного из известный поставщиков в РФ за 200р - https://hostline.ru

**Comment by olgapshen** [comment]
Ждём отмашки от небожителей @Malaxov16 @Marwin887

**Comment by sshiae** [comment]
Всё настроил

**Comment by olgapshen** [comment]
Круть!
