### ISSUE TITLE
Сохранение пользовательских данных в базе

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateBackend#15]
В рамках следующий парадигмы нашего MVP отображённому на диаграмме [тут](https://github.com/NorthGateVologda/NorthGateWiki/pull/2) необходимо создать табличные структуры для сохранения слоёв пользователя.

Вся структура базы должна коррелировать с результатами задачи [Написать User Story](https://github.com/NorthGateVologda/NorthGate/issues/5).

**Comment by olgapshen** [comment]
Тём, раскидай между ребятами.

**Comment by Marwin887** [comment]
Для слоя плотность населения необходимо 
1. Взять данные о домах архангельской области - https://аис.фрт.рф/opendata?gid=2216073&page=2&pageSize=12 
2. Выделить дома относящиеся к г. Архангельску
3. Жилую площадь в домах разделить на 24.1 м2/на человека
5. Сложить общее количество людей п.3 и сравнить с числом 346979 и рассчитать корректировочный коэффициент. 
6.  Рассчитать итоговое кол-во жителей для каждого дома с учетом коэффициента. 
7. Сформировать сетку шестиугольников размером 500 м от центра до угла шестиугольника (пешая доступность в рамках 15 минут)
8. Сгруппировать по координатам шестиугольники и  координаты домов. 
9. Сделать связку Дом-Шестиугольник, рассчитать для каждого шестиугольника количество проживающих людей и плотность населения на площадь шестиугольника.

**Comment by Marwin887** [comment]
Расчет коэффициента обеспеченности парками. 
1). Выявить текущие места размещения парков, выгрузить их координаты с помощью 2 gis парсера https://github.com/interlark/parser-2gis/wiki https://2gis.ru/arkhangelsk/search/Парки%20и%20скверы%20?m=40.715501%2C64.540854%2F10.75
2) Выгрузить все объекты по запросам "еда", "Достопримечательности" .......   через 2 GIS  парсер, достопримечательности,
......

**Comment by olgapshen** [comment]
> 1). Взять данные о домах архангельской области - [https://аис.фрт.рф/opendata?gid=2216073&page=2&pageSize=12](https://%D0%B0%D0%B8%D1%81.%D1%84%D1%80%D1%82.%D1%80%D1%84/opendata?gid=2216073&page=2&pageSize=12)
> 
> 2). Выделить дома относящиеся к г. Архангельску

Предлагаю вот эти два пункта как раз реализовать через Nifi. Это будет супер круто, так как во первых мы покажем супер уровень в данной сфере (статистика, большие данные, машинное обучение) через перспективу ETL, во вторых резко сэкономим вычислительные ресурсы системы загрузив данные единожды без необходимости постоянно подгружать. От @sshiae нужно будет добить тему с авторизацией с Nifi, а я тогда запилю всю интеграцию ETL. Возможно на бекенде понадобиться экспорт функции К КОТОРОЙ будет обращаться Nifi дабы та проксировала запрос на аис.фрт.рф.

Ребята!!! Это будет реально супер круто и надо будет обязательно отобразить это в следующей презентации. Сейчас поставлю себе задачу.

**Comment by olgapshen** [comment]
> 3). Жилую площадь в домах разделить на 24.1 м2/на человека
> 
> 4). Сложить общее количество людей п.3 и сравнить с числом 346979 и рассчитать корректировочный коэффициент.
> 
> 5). Рассчитать итоговое кол-во жителей для каждого дома с учетом коэффициента.
> 
> 6). Сформировать сетку шестиугольников размером 500 м от центра до угла шестиугольника (пешая доступность в рамках 15 минут)
> 
> 7). Сгруппировать по координатам шестиугольники и координаты домов.
> 
> 8). Сделать связку Дом-Шестиугольник, рассчитать для каждого шестиугольника количество проживающих людей и плотность населения на площадь шестиугольника.

Вот это вынесу в отдельную задачу по актуализации модели вычисления плотности населения.

**Comment by olgapshen** [comment]
> Расчет коэффициента обеспеченности парками для г. Архангельска

[Задача](https://github.com/NorthGateVologda/NorthGate/issues/31)

**Comment by sshiae** [comment]
Закрываем?

**Comment by Marwin887** [comment]
Да

вт, 15 авг. 2023 г., 13:29 Shirkunov Artyom ***@***.***>:

**Comment by olgapshen** [comment]
Собственно то говоря, так и не сохранили, но ладно :) Потом в новых проектах будем сохранять.
