### ISSUE TITLE
Объединить лишние слои Docker-а

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateBackend#16]
https://github.com/NorthGateVologda/NorthGateBackend/blob/3688bd28df25958d0d65dd2c84a3a56658393d7d/Dockerfile#L15

Каждая команда Docker-а это целый слоище, который занимает кучу места.
Мне кажется можно сразу сделать `COPY . app` а потом все:

```
RUN apt-get update -y \
    && apt-get upgrade -y \
    && pip install --upgrade pip \
    && pip install -r requirements/dev.txt \
    && apt-get install -y gdal-bin libgdal-dev
```

**Comment by olgapshen** [comment]
Тём, если Dockerfile уже собирается в рамках Backend-а то может его удалить из Swarm-а?

**Comment by olgapshen** [comment]
@sshiae ты же убрал лишние слои?

**Comment by sshiae** [comment]
Лишние слои убрал, задачу закрываю

**Comment by olgapshen** [comment]
Супер!
