### ISSUE TITLE
Объединить ENV-ы в одну команду

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateBackend#17]
https://github.com/NorthGateVologda/NorthGateBackend/blob/3688bd28df25958d0d65dd2c84a3a56658393d7d/Dockerfile#L3

Все ENV-ы мне кажется можно объединить в один с несколькими переменными. Каждая команда это целый слощие Docker-а.

**Comment by olgapshen** [comment]
Тёма, если готово, то пожалуйста закрывай.

**Comment by olgapshen** [comment]
Смотрю в `main` `ENV` уже [один](https://github.com/NorthGateVologda/NorthGateBackend/blob/de16e4dfa48f20af46204f697f7120ddd0bed0f2/Dockerfile#L3)...
@sshiae , не забывайте актуализировать задачи.

**Comment by sshiae** [comment]
Точняк, забыл про задачу, ENV поменял в Dockerfile, задачу закрываю, теперь там будет только одна команда
