### ISSUE TITLE
Dockerfile-ы и Swarm

### ISSUE THREAD

**Issue by olgapshen** [NorthGateVologda/NorthGateBackend#8]
https://github.com/NorthGateVologda/NorthGateBackend/blob/35f7b934819811948379aef3cf309eea2349fd8e/Dockerfile#L1

Надо решить где консолидировать Докерфайлы, думаю может лучше все Dockerfile-ы держать в Swarm-е?

**Comment by sshiae** [comment]
Да, я сейчас в Swarm добавляю Dockerfile Отдельно, но я их изменяю немного, чтобы удобнее было из Swarm деплоить

![image](https://github.com/NorthGateVologda/NorthGateBackend/assets/72744219/b104e6a0-1a13-4a16-ba19-66ab4c1458a4)

**Comment by olgapshen** [comment]
А ты хочешь чтобы эти файлы были сразу в нескольких репозиториях? Мне кажется надо что бы только в одном?...

**Comment by sshiae** [comment]
я решил, что незачем держать еще докер файлы в каждом проекте, поэтому удалил из всех проектов и теперь они централизованно в одном репозитории со всеми bash скриптами лежат
